/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package batalla.naval;

/**
 *
 * @author hp
 */
public class Main extends JFrame{
	
	private BattleShip batalla;
	private PanelLogin panelLogin;
	
	public Main() {
		batalla = new BattleShip();
		panelLogin = new PanelLogin();
		panelLogin.botonLogin.addActionListener(new AccionLogin());
		
		setContentPane(panelLogin);
		
		setTitle("BattleShip");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		pack();
		setLocationRelativeTo(null);
		setResizable(false);
		setVisible(true);
	}

	public static void main(String[] args) {
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				new Main();	
			}
		});
	}
	
	//Clases ActionListener para PanelLogin
	private class AccionLogin implements ActionListener {
		@Override
		public void actionPerformed(ActionEvent e) {
			
			String[] datos = panelLogin.getDatosLogin();
			if (datos != null) {
				if (batalla.validarLogin(datos))
					JOptionPane.showMessageDialog(null, "Login Aceptado");
				else
					JOptionPane.showMessageDialog(null, "Login Rechazado");
			}
			
		}
	}
}

    /**
     * Creates new form Main
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

